#+TITLE:     Memorandum of Understanding
#+AUTHOR:    Clifford Wulfman
#+EMAIL:     cwulfman@Princeton.EDU
#+DATE:      2014-06-23
#+LANGUAGE:  en
#+OPTIONS:   H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc

* Summary
  The Blue Mountain Project, based at Princeton University, and the
  Institute for Corpus Linguistics and Text Technology (ICLTT) –
  Research Group: Literature in Transition / AAC Austrian Academy
  Corpus (hereafter “LIT/AAC”), recognize common research interests
  and acknowledge a desire to engage in a general exchange of
  information about research progress made in the field of digital
  editions, in particular as concerns avant-garde magazines.  This
  document outlines the nature of this understanding.

  *Nota Bene* This document is not legally binding.

* The Understanding
  The Blue Mountain Project and the LIT/AAC group of the ICLTT share a
  common research interest in the application of digital technologies
  to the study of avant-garde magazines.  Members of the two groups
  have collaborated at conferences.  In order to promote a productive
  exchange of information about the work of both groups, Blue Mountain
  asks Dr. Hanno Biber of ICLTT to serve on its advisory board, in
  which capacity he will participate (remotely when necessary) in a
  yearly advisory-board meeting.
