#+TITLE:    Periodical Studies and the Digital Turn
#+AUTHOR:    Clifford Wulfman
#+EMAIL:     cwulfman@Princeton.EDU
#+DATE:      2012-11-04 Sun
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:



* Abstract
  The last decade has witnessed the rise of periodical studies -- an
  interdisciplinary area of research driven by the so-called "cultural
  turn" in literature departments and the development of large-scale
  digital archives (Latham and Scholes 2006).  Magazines pose
  theoretical and practical problems for digital humanists: they challenge
  assumptions about form, format, temporality, genre, and authority in
  ways that affect text encoding, optical-character-recognition, and
  descriptive metadata creation.

  This paper draws on the experience of the venerable Modernist
  Journals Project (http://modjourn.org) and the recently launched
  Blue Mountain Project
  (http://library.princeton.edu/projects/bluemountain/) to review the
  state of the digital periodical studies: the challenges posed by
  historical periodicals; a variety of pragmatic approaches; and the
  desirability of developing a cyberinfrastructure to support the
  discovery, capture, encoding, and dissemination of these critical
  cultural artifacts.

  Magazines are, by definition, miscellaneous (Scholes & Wulfman).  As
  miscellany, they often confound generic distinctions used to
  describe, winnow, and divide content.  Magazines complicate the
  separation of form from content so often made in the encoding of
  historical books.  Magazine layouts are frequently complex mixtures
  of text and image, editorial content and advertisement, which have
  been crafted to produce an effect on the reader (an affirmation of
  Marshall McLuhan's often cited remark about the medium being the
  message and an example of Roman Jacobson's poetic function of
  language). 

  Magazines complicate traditional notions of what constitutes a work.
  Most scholars have addressed the atomic content of magazines (the
  articles, ads, or illustrations) without considering the context in
  which those content units appear: discrete issues produced
  periodically under a common title and/or common editor.  Recent
  scholarship (see, for example, Ardis; Binckes; the Journal of Modern
  Periodical Studies) has begun to examine the magazine as an object
  in itself.

  The availability of screen-readable page images and
  machine-searchable plain-text transcriptions has facilitated
  periodical studies, but more remains to be done.  This paper
  concludes by presenting a format for encoding magazines (using TEI
  P5 and ALTO) that supports fielded metadata indexing, full-text
  search, and integration with the semantic web.

