#+TITLE:     A Magazine Ontology
#+AUTHOR:    Cliff Wulfman
#+EMAIL:     cwulfman@Princeton.EDU
#+DATE:      2012-11-29 Thu
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
* An Ontology of Periodicals and Magazines
  In information science, an /ontology/ is a formal representation of
  the concepts in a domain and the relationships among those concepts.
  "A formal, explicit specification of a shared conceptualisation"
  (Gruber, Thomas R. (June 1993). "A translation approach to portable
  ontology specifications" (PDF). Knowledge Acquisition 5 (2):
  199–220.)

  I am trying to design an ontology of magazines.  As we transform
  historical magazines into digital formats, we inevitably encounter
  problems of representation, at both the physical level of wrappers,
  covers, pages, spreads, inserts, gatefolds, etc. and at the logical
  level of articles, advertisements, heads, bylines, art, etc.  The
  task of creating an ontology is complicated by the variation in
  formats, concepts, and terminology in different countries and over
  time.  

  This work is, therefore, preliminary.  I have begun by assembling
  terms from various glossaries and text books from Britain and the
  US, some published mid-twentieth century, some on the
  world-wide-web.  From these terms, I have attempted to create a
  functional definition that can be encoded as a <docWORKS-Definition>
  document. 
** Major Divisions
  Folks in the trade distinguish between /editorial/ and /advertising/
  (the former is the "real content" of the magazine; the latter pays
  the bills); they seem to talk about the "ad/ed" ratio, for example.
*** Periodicity
    Magazines are periodicals by definition, even if they end up only
    appearing once.  The release of a magazine into circulation is
    called an /issuance/, and an instance of an issuance -- a copy --
    is called an /issue/.

    The issues of well-behaved periodicals, like scholarly journals,
    which have regular periodicity and long lives, are often gathered
    together and bound into /volumes/.  Volumes are usually
    anticipated: the page numbering of the issues that will constitute
    a volume is often sequential, and an index of the past year's
    volume is sometimes published with the first issue of the new
    (publication) year.  Some publishers produced and sold the volumes
    as collections; in other cases, libraries or collectors bound them
    privately.  Not all magazines were conceived in volumes, however.

    Some magazines issued /supplements/ -- separately bound issuances
    circulated on the same day as a regular issue or at some special
    time, for a special occasion (Christmas supplements, for example).
*** Physical Arrangement
    Most magazines were circulated in /covers/, made of heavier paper,
    which protected and bound the inner pages.  In addition, magazines
    sent through the post were often encased in plain-paper /wrappers/
    to protect the covers, which, being the first part of a magazine
    to strike a reader's (or buyer's) eye, were often lavishly
    illustrated.  Indeed, the front outer cover was often used as a
    canvas.  Other magazines -- more formal -- presented only a
    masthead and a table of contents.  The back outer cover and the
    inner covers were usually reserved for advertising.

    Not all magazines bore covers, however.  Some presented as
    newspapers, with a /masthead/ (the name of the magazine and,
    often, publication information: date and place of publication,
    price, and sequence number), a /table of contents/, and then the
    lead content.

    Most magazines (the ones we're considering here, at any rate)
    were, like books, printed on presses on large sheets of paper
    called /broadsides/ and then folded into /gatherings/ or
    /signatures/, which were then cut and bound.  The rectangular
    pieces of paper that resulted from this folding and cutting were
    called /leaves/, and each side of a leaf was called a /page/.

    Books and magazines are almost always designed to open 180 degrees
    and lie flat on a surface for reading.  Pages, then, almost always
    present in pairs: a page on the left (the /verso/) and a page on
    the right (the /recto/).  The valley formed by the juncture of
    bound pages is called the /gutter/.

    Book and magazine designers have long attended to the way readers
    encounter the messages conveyed through typography and composition
    and have often designed layouts that incorporate both verso and
    recto pages.  Advertisers are particularly attuned to the
    placement of their messages and covet particular spots -- the page
    opposite an important text, for example, often costs more.  It is
    probably best, then, to think of magazines not as a sequence of
    pages, but as a sequence of two-page, verso-recto /spreads/.

    It was not uncommon for magazines to break the recto/verso
    pagination with /foldouts/ that comprised two (or more) uncut
    pages folded at the outer edge of the issue which, when opened,
    displayed as a three-page spread.
*** Logical Arrangement
    The magazine trade draws a major distinction between /editorial/
    matter and /advertising/: the former is the raison d'etre for the
    magazine; the latter pays the bills.  The "ad/ed" ratio -- the
    percentage of the magazine devoted to editorial matter and that
    reserved for advertisers -- is often a bone of contention between
    editors and publishers.  The ad/ed distinction is present at the
    outset, then the layout of an issue is planned.

    There are, typically, two sorts of advertisements: /display ads/,
    which sometimes stand alone and usually employ distinctive
    typography and illustration; and /classified ads/, usually
    text-only, which appear in distinct sections (that is, they are
    /classified/).  

    Of editorial matter there are kinds without number: articles,
    fiction, poetry, features, editorials, op-eds, reviews; cartoons,
    photographs, prints, engravings, illustrations, and so on and so
    on.  Any markup project that chooses to distinguish among the
    various subtypes of editorial matter must squarely confront the
    problems of classification, ambiguity, and interpretation.
*** Text and Image
    The printed matter of a magazine is also distinguished by its
    method of composition. /Text/ set in type is distinguished from
    /art/ or /graphics/, which are printed from different sorts of
    surfaces, or /matrices/ (relief, intaglio, planographic).

    The graphics (usually called the /art/) are further distinguished
    into /original (prints)/ and /reproductions./

    Not infrequently, original art will be /tipped in:/ printed
    separately and glued onto a page of the magazine.
*** Layout (Zone Types)
    [ TK ]
** A Formulation
*** Physical
    (NB: this formulation does not address the problem of foldouts.)
   - Issue
     - Front Cover
       - Outside Front Cover (OFC)
       - Inside Front Cover (IFC)
     - Body
       - page+
     - Back Cover
       - Inside Back Cover (IBC)
       - Outside Back Cover (OBC)
   - Supplement
     - Same as issue

   An alternative makes the concept of a /spread/ explicit:

   - Issue
     - Front Cover
       - Outside Front Cover (OFC)
       - Inside Front Cover (IFC)
     - Body
       - page +
	 - recto
	 - verso
     - Back Cover
       - Inside Back Cover (IBC)
       - Outside Back Cover (OBC)



    

  - Page Classes
    - Cover
      - Front
	- Outer
	- Inner
      - Back
	- Inner
	- Outer
    - Inside
*** Layout
  - Zone Classes
    - head
    - subhead
    - copy
    - logo
    - caption
    - graphic
    - byline
    - ornament
    - separator
    - folio (page number)
    - date line
    - name plate
    - masthead
    - cover line(s)
    - deck
*** Logical
    This taxonomy of content types should be applicable by degree to
    magazine content: it is enough to classify an item as /art/, but
    if the encoder can determine whether or not it is /original/ or a
    /reproduction/, he or she may say so.  Even more so in the case of
    textual content, where genre may be difficult to determine.

  - Content Types
    - Advertisement
      - Display
      - Classified
    - Editorial
      - art
	- original
	- reproduction
      - piece/contribution
	- announcement
	- article
	- cartoon
	- editorial piece
	- feature
	- fiction
	- installment
	- item
	- notice
	- obituary
	- op-ed
	- poem
	- score
	- review
	- story
** A Gathering of Vocabularies
   The following sections contain terms gleaned from various sources.
   This is, of course, a haphazard way to generate an ontology, but it
   is a start.
*** General Terms
    - advertisement
    - announcement
    - article
    - artwork
    - banner headline
    - by-line
    - cartoon
    - centerfold
    - classified ad
    - supplement
    - column
    - comic strip
    - contribution
    - copy
    - editorial
    - feature
    - headline
    - installment
    - item
    - lead
    - leader
    - listing
    - masthead
    - notice
    - obituary
    - op-ed
    - piece
    - review
    - spread
    - story
    - supplement
    - write-up

    - body copy

    - display copy
      - headlines
      - captions

*** Cover terms
   - masthead
   - nameplate
   - folio
   - cover line(s)
   - date line
*** Other terms
   - spread
   - head
   - byline
   - subhead
   - deck
   - art
   - credit
   - kicker

   - display ads :: appear on the same page as, or on pages adjacent
                    to, editorial content.  Come in variety of sizes,
                    usually FP (full page), RHP (right-hand page), QP
                    (quarter page), HPH and HPV (half page horizontal
                    and vertical).
   - classified ads :: text-only ads, usually appearing in distinct
                       sections.  Book ads are of this type.

*** Terms from Magforum.com/glossary
   - body copy :: main text on a page
   - content :: editorial matter
   - folio :: Page number in a typeset text
   - IBC, IFC :: inside back cover, inside front cover
   - logo :: the name of a publication in a specific type face used
	     on the cover and for the masthead
   - masthead :: the name of a publication traditionally printed at
		 the top of the first editorial page, often as a
		 logo and often accompanied by issue number and
		 date. 2) The word has evolved to encompass the box
		 that gives details of the publisher, staff and
		 contact information. Different publishers put this
		 information in different places: on the contents
		 page or on the leader page or on one of the pages
		 near the back of a magazine. Again, it is often
		 acompanied by the magazine's logo.  3) also used
		 for the logo - the name of the magazine in its
		 chosen font on the front cover.
   - OBC :: outside back cover
   - gatefold cover :: cover that folds out.
   - RH :: Right-hand (page)
   - RHFM :: righ-hand (page), facing (editorial) matter
   - TOC :: table of contents

*** Notes
****  /editorial/ and /content/
      /editorial/ and /content/ are often synonymous; both mean
      non-advertising text.  /editorial/ may also be "An article
      expressing the views of the editor or publication policy."
**** arrangement of ads and ed related to some extent on printing
     Barnard (Magazine and Journal Production) shows (pp. 23-24) that
     certain sections are printed before others, so that the signatures
     that might need to be changed to accommodate late-submission ads
     can be printed last.

*** From http://www.woodenhorsepub.com/glossary.htm
   - DECK :: The deck is intended to tease the readers into reading
	     the article. It is placed right below the title and
	     above the first paragraph and is often set in bold. It
	     can actually be the first paragraph of the article but
	     most often, it's a separate piece of copy.

   - FOB :: "Front of the book" the beginning pages of a magazine,
	    usually consisting of shorter editorial material, such
	    as columns and departments.  See BOB.

	    The space between the FOB and the BOB is sometimes
	    called the WELL; a place without ads.

   - Gate Fold :: A special page in a magazine, usually for an ad,
		  which is printed on a larger piece of paper and
		  folded to fit the size of the magazine and open
		  like a gate.

   - INDICIA :: A page in a publication that contains publication
		name, date of issue, frequency, serial number,
		publication office, subscription price, and notice
		of entry information, appearing in the first five
		pages.

   - ISSUE :: All the copies of a periodical with the same cover
	      date and distributed at the same time.

   - FOLIO NUMBER :: a page number

   - MAQUETTE :: The layout or roadmap of the magazine, generated by
		 the advertising department, it shows exactly where
		 editorial and ads will appear.

   - SPREAD :: A single advertisement printed over two facing pages.

   - WELL :: The main section of a magazine where the feature
	     articles are published.  It's usually located in the
	     middle surrounded by columns and departments.
	     
