#+TITLE:     Memorandum of Understanding between The Blue Mountain Project and the Modernist Journals Project
#+AUTHOR:    Clifford Wulfman
#+EMAIL:     cwulfman@Princeton.EDU
#+DATE:      2014-05-22 Thu
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

* Summary
  The Blue Mountain Project, based at Princeton University, and the
  Modernist Journals Project, based at the University of Tulsa and
  Brown University, have established a foundation on which to
  coordinate future work to the mutual benefit of both projects.
  This document outlines the nature of this understanding.

  *Nota Bene* This document is not legally binding.

* Background
  The Modernist Journals Project (MJP) and the Blue Mountain Project
  share a common history, common goals, and a common stakeholder base.
  The two projects have complementary areas of strength at this point
  in their development:

  - Blue Mountain is based in a library, with strong institutional
    support for digital conversion and preservation.  Blue Mountain
    has a mandate to foster collaboration and to work to create a
    sophisticated, robust, and sustainable cyberinfrastructure for the
    creation of well-encoded, well-structured digital editions of
    relevant materials, and for supporting and developing ways to
    discover them through traditional and modern discovery tools. We
    are committed to extending traditional modes of access (screen
    readers and pdfs) by designing and building tools and APIs to
    support contemporary research methods, such as data mining and
    corpus analysis. Blue Mountain has a growing base of support among
    American and international institutions, such as MoMA, NYPL,
    CLARIN, the Austrian Institut für Corpuslinguistik und
    Texttechnologie, etc.

  - The MJP is a fixture in modern periodical studies, with an active
    user community engaged in research and teaching. In its current
    phase of development, it is deeply focused on developing tools and
    communities for interacting with digital editions of
    magazines. Etc, etc. -- [JEFF: lay out the MJP's areas of
    strength in greater detail.]

  Blue Mountain and the MJP share a common heritage and a common
  history.  Princeton University Library, where the Blue Mountain
  Project is based, has, since 2006, partnered with the MJP to provide
  the latter with materials for its digital collection.  The founder
  and current director of the Blue Mountain Project was formerly the
  technical director of the MJP and conceived Blue Mountain explicitly
  to complement the MJP in its collections and in its aims.

  While wishing to maintain our independence, we recognize that both
  projects, and the community of students, scholars, libraries, and
  museums, would benefit from an explicit pooling of resources and an
  explicit alignment of aims and goals.  Specifically,

  - A common repository structure for the preservation of digital
    editions, in collaboration with the HathiTrust;

  - An interoperability infrastructure that would, among other
    things, enable cross-searching and cross-referencing;

  - A common presentation API that enables the creation of exhibits,
    presentations, etc. in mainstream content-management systems like
    Drupal, Omeka, etc., as well as the online display and annotation
    of digital editions (see IIIF and Mirador).

  - An ongoing dialog among common stakeholders to coordinate the
    growth of online resources for the study of modern and
    avant-garde magazines: specifically, to pursue complementary
    collection development strategies whenever possible and to
    coordinate the development of shared authority resources like
    biographical dictionaries and gazetteers.

* Provisions of the Agreement
** A Common Advisory Board
   While maintaining separate governance structures, Blue Mountain and
   the MJP will form a common board of advisors drawn from both
   projects and from the stakeholder community.  This board will meet
   (physically or virtually) once a year[fn:1] to receive updates from both
   projects and from stakeholder representatives (researchers,
   teachers, technologists, funders) and to produce recommendations,
   which will be communicated formally to each project.
** A Mutual Asset Management Structure
   Blue Mountain and the MJP will investigate ways to share the
   institutional burdens of asset management and preservation in
   order to minimize unnecessary redundancy and improve the efficient
   expenditure of grant funds on asset preservation.
** Complementary Discovery Interfaces
   Blue Mountain and the MJP will also investigate ways to facilitate
   stakeholders' mutual, simultaneous access to their resources.
   Possible methods include federated searching through a common
   portal (such as, perhaps, ModNets) and the development of common
   citation methods.
** Other Provisions to be Added
   Suggestions?

* Footnotes

[fn:1] The annual conference of the Modernist Studies Association might
be a convenient occasion for this board meeting.


