* An Ontology of Periodicals and Magazines
  In information science, an /ontology/ is a formal representation of
  the concepts in a domain and the relationships among those concepts.
  "A formal, explicit specification of a shared conceptualisation"
  (Gruber, Thomas R. (June 1993). "A translation approach to portable
  ontology specifications" (PDF). Knowledge Acquisition 5 (2):
  199–220.)

  Form and Matter

* Physical Structure: Form
  The notion of composition: that is the assembly of a whole from parts.

  - copy :: the main text part of an article or advertisement, as
            distinct from logos, headlines, subheadings, captions, and
            graphics.

** Printer's Units
   - sheet
   - folio
   - quarto
   - octavo
   - page
   - quire
** Binder's Units
   - gathering

* Terms
    - advertisement
    - announcement
    - article
    - artwork
    - banner headline
    - by-line
    - cartoon
    - centerfold
    - classified ad
    - supplement
    - column
    - comic strip
    - contribution
    - copy
    - editorial
    - feature
    - headline
    - installment
    - item
    - lead
    - leader
    - listing
    - masthead
    - notice
    - obituary
    - op-ed
    - piece
    - review
    - spread
    - story
    - supplement
    - write-up

    - body copy

    - display copy
      - headlines
      - captions

** Cover terms
   - masthead
   - nameplate
   - folio
   - cover line(s)
   - date line
** Other terms
   - spread
   - head
   - byline
   - subhead
   - deck
   - art
   - credit
   - kicker

   - display ads :: appear on the same page as, or on pages adjacent
                    to, editorial content.  Come in variety of sizes,
                    usually FP (full page), RHP (right-hand page), QP
                    (quarter page), HPH and HPV (half page horizontal
                    and vertical).
   - classified ads :: text-only ads, usually appearing in distinct
                       sections.  Book ads are of this type.


** From Magforum.com/glossary
   - body copy :: main text on a page
   - content :: editorial matter
   - folio :: Page number in a typeset text
   - IBC, IFC :: inside back cover, inside front cover
   - logo :: the name of a publication in a specific type face used
	     on the cover and for the masthead
   - masthead :: the name of a publication traditionally printed at
		 the top of the first editorial page, often as a
		 logo and often accompanied by issue number and
		 date. 2) The word has evolved to encompass the box
		 that gives details of the publisher, staff and
		 contact information. Different publishers put this
		 information in different places: on the contents
		 page or on the leader page or on one of the pages
		 near the back of a magazine. Again, it is often
		 acompanied by the magazine's logo.  3) also used
		 for the logo - the name of the magazine in its
		 chosen font on the front cover.
   - OBC :: outside back cover
   - gatefold cover :: cover that folds out.
   - RH :: Right-hand (page)
   - RHFM :: righ-hand (page), facing (editorial) matter
   - TOC :: table of contents

** Notes
***  /editorial/ and /content/
     /editorial/ and /content/ are often synonymous; both mean
     non-advertising text.  /editorial/ may also be "An article
     expressing the views of the editor or publication policy."
*** arrangement of ads and ed related to some extent on printing
    Barnard (Magazine and Journal Production) shows (pp. 23-24) that
    certain sections are printed before others, so that the signatures
    that might need to be changed to accommodate late-submission ads
    can be printed last.

** From http://www.woodenhorsepub.com/glossary.htm
   - DECK :: The deck is intended to tease the readers into reading
	     the article. It is placed right below the title and
	     above the first paragraph and is often set in bold. It
	     can actually be the first paragraph of the article but
	     most often, it's a separate piece of copy.

   - FOB :: "Front of the book" the beginning pages of a magazine,
	    usually consisting of shorter editorial material, such
	    as columns and departments.  See BOB.

	    The space between the FOB and the BOB is sometimes
	    called the WELL; a place without ads.

   - Gate Fold :: A special page in a magazine, usually for an ad,
		  which is printed on a larger piece of paper and
		  folded to fit the size of the magazine and open
		  like a gate.

   - INDICIA :: A page in a publication that contains publication
		name, date of issue, frequency, serial number,
		publication office, subscription price, and notice
		of entry information, appearing in the first five
		pages.

   - ISSUE :: All the copies of a periodical with the same cover
	      date and distributed at the same time.

   - FOLIO NUMBER :: a page number

   - MAQUETTE :: The layout or roadmap of the magazine, generated by
		 the advertising department, it shows exactly where
		 editorial and ads will appear.

   - SPREAD :: A single advertisement printed over two facing pages.

   - WELL :: The main section of a magazine where the feature
	     articles are published.  It's usually located in the
	     middle surrounded by columns and departments.
	     
** From http://www.tpub.com/journalist/75.htm
   FRONT-PAGE FOLIO LINE. - A front-page folio line joins the
   nameplate and consists of the volume number (the number of years
   the publication has been in print), the issue number (the number of
   issues published within the present year), command, location (city
   and state), and date of publication. It does not carry a page
   number and is usually separated from the flag by a border and a
   cutoff rule or by two cutoff rules.

   INSIDE PAGE FOLIO LINE. - An inside page folio line generally runs
   at the top of each page. It also can run as part of a flag that
   appears on special pages or within the masthead on the editorial
   page. The inside page folio line consists of the publication date
   (left corner of the page), name of the newspaper (centered) and the
   page number (right corner of the page). An inside page folio line
   is normally separated from the rest of the page by a cutoff rule,
   but as you can see in figure 8-15, this is not a requirement.
** from http://www.scribd.com/doc/31407922/Newspaper-Layout-Presentation
   Flag :: a display used by a newspaper (or magazine) to indicate
   section pages or special pages.

* Major Divisions
  Folks in the trade distinguish between /editorial/ and
  /advertising/ (the former is the "meat" of the magazine; the latter
  pays the bills); they seem to talk about the "ad/ed" ratio, for
  example.

  - Issue
    - Front Wrapper
      - Outside Front Cover (OFC)
      - Inside Front Cover (IFC)
    - Body
      - Sections
    - Back Wrapper
      - Inside Back Cover (IBC)
      - Outside Back Cover (OBC)

  

  Paper & Printing Trades Journal

Title: Paper & printing digest.
Published/Created: [Cleveland, etc., Cleveland Paper Co., etc.] 
Description: 5 v.: ill. (part col., incl. ports., maps, facsims., mounted samples) diagrs. 22 cm. 
v. [1]-5; Jan. 1935-Dec. 1939. 
Notes: Title varies slightly. 
Edited by W. B. Wheelwright. 
Subject(s): Paper industry -- Periodicals ; Printing -- Periodicals
Related name(s): Wheelwright, William Bond, 1879- ed ;
Wheelwright, William Bond, 1879- comp. Paper trade terms
Other Title(s): Paper and printing digest 
ISBN/ISSN: 0097-4269 
Summary: Vol. 4, no. 2-11 include sections: Paper trade terms, a glossary for the allied trades, printing and paper, compiled by W. B. Wheelwright. 
Voyager Bib ID: 4557978 

The bookman's glossary

Applied design for printers
