* Timeline
** [2013-06-14 Fri] Email from GK
   Requesting conference call to discuss Blue Mountain SOW.
** [2013-06-18 Tue] conference call
   CW, GK, (Ann Roberts) discuss the need to raise price.
** [2013-06-25 Tue] Email from CW -> GK
   CW asks GK for ballpark figure on future conversion costs (more than
   .52/page but less than ??) for new grant proposal

   That sounds great, Greg; I appreciate it.  The sooner I can get at
   least a ballpark estimate on future conversion costs (more that
   $.52/page but less than ??) the sooner I'll be able to refine our
   list to reflect NEH funding caps.

   Cliff Wulfman
   cwulfman@Princeton.EDU
   
   
   
   
   On Jun 25, 2013, at 12:40 PM, Greg Kullman wrote:
   
   Thanks Cliff. We'll have our team take a look and let you know what
   questions we have. In the mean time, our team is putting together a
   report on the work we've done thus far, attempting to put the
   various publications in different buckets by complexity. We'll use
   those same buckets to differentiate the new titles coming in as
   well and will share this information with you before moving forward
   with the rest of the work.

   Best,
   Greg
   

   On Mon, Jun 24, 2013 at 10:16 AM, Clifford E. Wulfman
   <cwulfman@princeton.edu> wrote: Dear Greg and Ann,
   
   It was good to talk with you last week.  In the next several days,
   I will assemble PDFs of sample issues from the remaining Blue
   Mountain Phase I titles, so that we can begin to re-evaluate the
   cost of completing this work.

   At the same time, I am attaching an RFP for the next phase, which I
   mentioned briefly in our phone conversation.  Our proposal deadline is
   July 11 -- not long from now -- and I need an estimated price for the
   budget as soon as I can get it.
   
   As I mentioned in our phone conversation, I don't think this phase is
   going to be as challenging as the previous phase has been: many of
   these are pretty old-fashioned in their layout, if not in their
   contents.
   
   
   Let me know if you have any questions: it will be easiest to reach me
   via email, but I can arrange a phone call any time.
** [2013-07-16 Tue] Email from GK
   I should have an answer for you in the next day or so regarding
   Phase I. I think rather than move to variable pricing for the
   different publications, we would recommend $0.70/page. We've found
   it difficult to group the publications into different buckets and
   instead think an average per page price might work best. We're also
   confident we can process all publications. Our productivity has
   improved and we're confident we can do the work moving forward at
   $0.70/page (I realize we need to discuss if that's even a
   possibility). We accept that we priced it at $0.56/page when we did
   the contract a while back and will commit to that price for Phase I
   if necessary.
** [2013-08-12 Mon] email from GK requesting .70/page
   Says preparing an invoice and wants to charge .70/page
** [2013-08-14 Wed] GK sends first version of invoice 4172
   In an email from GK, as an attachment. Price is .70/page
** [2013-08-15 Thu] Greg withdraws first version
   In email.
** [2013-08-16 Fri] DDD billing sends second version of invoice 4172
   Price is .52/page
